### ISSUE TITLE
English language - Union Jack flag

### ISSUE THREAD

**Issue by salvatorecapolupo** [usrz/bootstrap-languages#17]
Hello, maybe I am missing something... 

can't find a way to include traditional english flag i.e https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/1200px-Flag_of_the_United_Kingdom.svg.png

Is this available in this library? Thanks in advance

**Comment by pfumagalli** [comment]
Not available.
